### ISSUE TITLE
Re-assigning IP to existing container kills host / Segfault

### ISSUE THREAD

**Issue by 46labs** [jpetazzo/pipework#79]
Environment
Ubuntu 14.04 LTS (GNU/Linux 3.13.0-30-generic x86_64)
Docker 1.1.1
Latest Pipework

Method to replicate issue:

Bring up a container with an ip using pipework:

ie. root@docker:~# pipework eth0 -i eth1 0b3 1.1.1.1/24@1.1.1.254

Then run the same command again after the container is up:

root@docker:~# pipework eth0 -i eth1 0b3 1.1.1.1/24@1.1.1.254
Segmentation fault

It segfaults the container, leave docker in a disk wait mode and hoses the physical host. The only method to get the host to do anything is to hard boot it. It will not respond to a restart inside of linux.

**Comment by lizf-git** [comment]
This is a kernel bug in ubuntu kernel, which has been fixed by this:

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=da37705cef30841616ed644ff33455bbc7374db0

I've asked the ubuntu kernel maintainer to apply this fix, so this bug should disappear after ubuntu updates its kernel to include the fix.

**Comment by dubglan** [comment]
We observe this when PIDs wrap and new container is created with the same PID as an old one. Even though the old container is stopped and removed properly with "docker stop; docker rm -fv" (that destroys "lower" part of macvlan interface), "upper" part survives:
> root@docker:~# ls -la /sys/class/net/eth2/upper*
> lrwxrwxrwx 1 root root 0 Apr 27 19:44 /sys/class/net/eth2/upper_ph2932eth2 -> ../../../../../virtual/net/eth2
> lrwxrwxrwx 1 root root 0 Apr 27 19:44 /sys/class/net/eth2/upper_ph2963eth2 -> ../../../../../virtual/net/eth2

This is enough to cause a panic. @lizf-git I don't know if the kernel fix helps here because macvlan device is partially removed, even if it doesn't panic, the result might be unexpected. Need to test this out. 

@helloIAmPau, @jpetazzo 
We temporarily patched pipework to add GUESTNAME to GUEST_IFNAME. After quick search I found only way to clean up upper interfaces: reboot the docker host. In our environment we destroy docker hosts regularly and recreate them from VM images so lingering upper interfaces don't pose a problem for us.

**Comment by dubglan** [comment]
Spoke too soon. There's 15 character limitation on the iface name, so had to resort to mktemp:
```
mkdir -p /tmp/ifaces
GUEST_IFNAME=$(basename $(mktemp --tmpdir=/tmp/ifaces XXXXXXXXXXXXXXX))
```
Not very beautiful, but works.

**Comment by brettnem** [comment]
What's the status of this bug. I'm still getting kernel panics. 

Thanks

**Comment by jpetazzo** [comment]
A fix is in the works; if this is a big blocker for you, feel free to contribute on #116, help will be greatly appreciated! Thank you.
